<<<<<<<< HEAD:w01/diary/migrations/0008_alter_content_cdate_remove_content_group_diary_and_more.py
# Generated by Django 5.1.3 on 2024-12-17 03:41
========
# Generated by Django 5.1.3 on 2024-12-18 11:28
>>>>>>>> 6a4eebe54a590c8fcedadb88b1311e536eb29c66:w01/diary/migrations/0004_alter_content_cdate_remove_content_group_diary_and_more.py

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_content_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cdate',
<<<<<<<< HEAD:w01/diary/migrations/0008_alter_content_cdate_remove_content_group_diary_and_more.py
            field=models.DateField(default=django.utils.timezone.now),
========
            field=models.DateTimeField(default=django.utils.timezone.now),
>>>>>>>> 6a4eebe54a590c8fcedadb88b1311e536eb29c66:w01/diary/migrations/0004_alter_content_cdate_remove_content_group_diary_and_more.py
        ),
        migrations.RemoveField(
            model_name='content',
            name='group_diary',
        ),
        migrations.AddField(
            model_name='content',
            name='group_diary',
            field=models.ManyToManyField(blank=True, to='diary.groupdiary'),
        ),
    ]
