# Generated by Django 5.1.3 on 2024-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('ndate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
